- name: Install Apache
  hosts: all
  become: true

  tasks:
  - name: install apache
    package:
      name: httpd
      state: present

  - name: start httpd
    systemd:
      name: httpd
      state: started
      enabled: yes
